<#
.SYNOPSIS
Automates SSL certificate management for Kiona WebPort using ACME/Let’s Encrypt.

.DESCRIPTION
This script performs complete end-to-end certificate handling for WebPort,
including CSR-based ACME issuance, certificate chain updates in the WebPort
SQLite database, PFX generation, keystore installation, firewall adjustments,
and optional email reporting.

PARAMETERS
  -failsafe
      Resets all SSL-related data without performing any ACME operations.
      Must NOT be combined with any other functional parameters.

  -IssueCert
      Performs ACME certificate issuance or renewal using the CSR stored in the
      WebPort database. Uses the selected Posh-ACME DNS plugin.

  -InstallPfx
      Builds the WebPort-compatible webport.p12 file and installs the resulting
      certificate into the LocalMachine\My certificate store.

  -DnsPlugin
      Specifies the DNS plugin used for ACME DNS-01 validation.
      Default plugin is "Azure".  
      List available plugins: Get-PAPlugin

  -Sendmail
      If provided, the script will analyze the runtime log and email either a
      “success” or “problem detected” report to the provided recipient(s).

  -CreateScheduledTask
      Creates a Windows Scheduled Task using PowerShell 7 that runs the script
      with the same effective parameters and working directory.

.NORMAL MODE
  • Reads CSR and CN from the WebPort SQLite database
  • Issues or renews certificates via ACME using the stored CSR
  • Supports any Posh-ACME DNS plugin
  • Updates leaf/intermediate/root certificates inside WebPort DB
  • Builds a WebPort-compatible P12 file
  • Installs certificate into LocalMachine\My (via InstallPfx)
  • Ensures firewall rules match the current ServerPort
  • Requires PfxPass from SecretStore

.FAILSAFE MODE
  • Clears SSL-related fields:
        SSLCSR, SSLPPK, SSLCAPC, SSLCAIC, SSLCARC, SSLCP
  • Removes webport.p12
  • Deletes matching certificates from the certificate store
  • Restarts WebPort
  • Performs NO ACME operations
  • Must NOT be combined with PfxPass

.EMAIL REPORTING
If -Sendmail is supplied, the script scans the IssueCert runtime log for
strings indicating failure (exception, error, fail, timeout, denied, invalid,
etc.):

  • If issues are detected:
        Sends an email titled "<CN> - Problem renewing certificate"

  • If no issues are detected:
        Sends an email titled "<CN> - Certificate renewed"

SMTP settings must exist in the WebPort database:
    smtpserver, smtpport, smtpssl, smtpencoding, smtpfrom, smtpuser  
    The password (smtppassword) is retrieved from SecretStore as SmtpPwd.

.SECRETSTORE USAGE
SecretStore is used to securely store sensitive script parameters:

  1. SecretManagement and SecretStore modules are ensured
  2. SecretStore is registered and set as default vault
  3. SecretStore is initialized if missing
  4. The unlock password is stored in securePassword.xml
  5. The vault is automatically unlocked during execution
  6. Secrets retrieved:
        • PluginArgs – DNS plugin configuration
        • PfxPass    – WebPort P12 password
        • SmtpPwd    – SMTP account password

.EXAMPLE
# Adding DNS plugin arguments to SecretStore:
Set-Secret -Name PluginArgs -Secret $pArgs
Set-Secret -Name PfxPass -Secret "MyStrongPassword"
Set-Secret -Name SmtpPwd -Secret "S3cur3!"

.EXAMPLE
# Listing secrets:
Get-SecretInfo

.EXAMPLE
# Retrieving a secret:
Get-Secret -Name PluginArgs -AsPlainText

.EXAMPLE
# Removing a secret:
Remove-Secret -Name PluginArgs

.EXAMPLE
# Resetting the SecretStore vault:
Unregister-SecretVault -Name SecretStore
Remove-Item "$env:LOCALAPPDATA\Microsoft\PowerShell\secretmanagement\secretstore" -Recurse -Force

.DNS PLUGIN SUPPORT
All Posh-ACME plugins are supported.  
Display plugin documentation:
    Get-PAPlugin -Plugin Azure      -Guide
    Get-PAPlugin -Plugin Cloudflare -Guide
    Get-PAPlugin -Plugin AcmeDns    -Guide

.ACME PROCESS
  • The CSR is generated by WebPort GUI
  • The script performs DNS-01 ACME validation
  • Leaf/intermediate/root certificates are written into the WebPort DB
  • Private key is taken from the certstore or DB (fallback scenario)

.NOTES
  • Requires PowerShell 7+
  • Requires administrative privileges
  • CSR must be created in WebPort GUI
  • Default DNS plugin is Azure but can be changed
  • Only InstallPfx performs certificate installation

.AUTHOR
    Original Author:  Magnus Ardström

.REVISION
    Version:            1.0.0   2025-11-09
    Version:            1.1.0   2025-11-17
    Version:            1.1.1   2025-11-18
       
#>


[CmdletBinding(DefaultParameterSetName="Normal")]
param(
    [Parameter(ParameterSetName="FailSafe", Mandatory=$true)]
    [switch]$failsafe,

    [Parameter(ParameterSetName="CreateScheduledTask", Mandatory=$true)]
    [switch]$CreateScheduledTask,

    [Parameter(ParameterSetName="Normal")]
    [Parameter(ParameterSetName="FailSafe")]
    [Parameter(ParameterSetName="CreateScheduledTask")]
    [string]$WebPortDataPath = "C:\ProgramData\WebPort",

    [Parameter(ParameterSetName="Normal")]
    [Parameter(ParameterSetName="FailSafe")]
    [Parameter(ParameterSetName="CreateScheduledTask")]
    [string]$WebPortProgPath = "C:\Program Files\WebPort",

    [Parameter(ParameterSetName="Normal")]
    [Parameter(ParameterSetName="FailSafe")]
    [Parameter(ParameterSetName="CreateScheduledTask")]
    [int]$ServerPort = "8090",

    [Parameter(ParameterSetName="Normal")]
    [Parameter(ParameterSetName="FailSafe")]
    [Parameter(ParameterSetName="CreateScheduledTask")]
    [switch]$IssueCert,

    [Parameter(ParameterSetName="Normal")]
    [Parameter(ParameterSetName="FailSafe")]
    [Parameter(ParameterSetName="CreateScheduledTask")]
    [switch]$InstallPfx,

    [Parameter(ParameterSetName="Normal")]
    [Parameter(ParameterSetName="FailSafe")]
    [Parameter(ParameterSetName="CreateScheduledTask")]
    [string]$DnsPlugin,

    [Parameter(ParameterSetName="Normal")]
    [Parameter(ParameterSetName="FailSafe")]
    [Parameter(ParameterSetName="CreateScheduledTask")]
    [string]$Sendmail  

)

$banner = @'
  _          _       ______                             _    __          __  _     _____           _   
 | |        | |     |  ____|                           | |   \ \        / / | |   |  __ \         | |  
 | |     ___| |_ ___| |__   _ __   ___ _ __ _   _ _ __ | |_   \ \  /\  / /__| |__ | |__) |__  _ __| |_ 
 | |    / _ \ __/ __|  __| | '_ \ / __| '__| | | | '_ \| __|   \ \/  \/ / _ \ '_ \|  ___/ _ \| '__| __|
 | |___|  __/ |_\__ \ |____| | | | (__| |  | |_| | |_) | |_     \  /\  /  __/ |_) | |  | (_) | |  | |_ 
 |______\___|\__|___/______|_| |_|\___|_|   \__, | .__/ \__|     \/  \/ \___|_.__/|_|   \___/|_|   \__|
                                             __/ | |                                                   
                                            |___/|_|                                                   
'@

Write-Host $banner -ForegroundColor Magenta

[string]$SqliteDllPath  = "$WebPortProgPath\System.Data.SQLite.dll"
[string]$WebPortDbPath  = "$WebPortDataPath\db\webport.sqlite"

$ErrorActionPreference = "Stop"

function step($t){ Write-Host "==> $t" -ForegroundColor Cyan }
function ok  ($t){ Write-Host "   ✓ $t" -ForegroundColor Green }
function warn($t){ Write-Host "   ⚠ $t" -ForegroundColor Yellow }
function err ($t){ Write-Host "   ✖ $t" -ForegroundColor Red }

function Read-WebPortSettings {
    if (!(Test-Path $SqliteDllPath)) { throw "SQLite DLL saknas: $SqliteDllPath" }
    if (!(Test-Path $WebPortDbPath)) { throw "DB saknas: $WebPortDbPath" }

    Add-Type -Path $SqliteDllPath

    $conn = New-Object System.Data.SQLite.SQLiteConnection("Data Source=$WebPortDbPath;")
    $conn.Open()

    $data = @{}

    try {
        # Läs DeviceGuid
        $cmd = $conn.CreateCommand()
        $cmd.CommandText = "SELECT DeviceGuid FROM settings LIMIT 1"
        $data.DeviceGuid = $cmd.ExecuteScalar()

        if (!$data.DeviceGuid) {
            throw "Ingen DeviceGuid hittades i databasen."
        }

        # Läs Key/Value-par
        $cmd = $conn.CreateCommand()
        $cmd.CommandText = "SELECT Key,Value FROM settings"
        $r = $cmd.ExecuteReader()
        while ($r.Read()) {
            $key = $r.GetString(0)
            $val = $r.GetString(1)
            $data[$key] = $val
        }
        $r.Close()
    }
    finally {
        $conn.Close()
    }

    return $data
}

function Get-WebPortServerPort {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [string]$WebPortDataPath
    )

    $confPath = Join-Path $WebPortDataPath "webport.conf"

    if (-not (Test-Path $confPath)) {
        throw "webport.conf saknas: $confPath"
    }

    try {
        $confRaw = Get-Content $confPath -Raw -ErrorAction Stop
        $conf    = $confRaw | ConvertFrom-Json -ErrorAction Stop
    }
    catch {
        throw "Kunde inte läsa eller parsa webport.conf → $($_.Exception.Message)"
    }

    if (-not $conf.default -or -not $conf.default.ServerPort) {
        throw "ServerPort saknas i webport.conf"
    }

    return [int]$conf.default.ServerPort
}

function Set-WebPortServerPort {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [string]$WebPortDataPath,

        [Parameter(Mandatory=$true)]
        [ValidateRange(1,65535)]
        [int]$ServerPort
    )

    Write-Host "==> Uppdaterar WebPort ServerPort…" -ForegroundColor Cyan

    $confPath = Join-Path $WebPortDataPath "webport.conf"

    if (-not (Test-Path $confPath)) {
        Write-Host "⚠ webport.conf saknas – skapar ny standardfil" -ForegroundColor Yellow
        
        $defaultConf = @{
            default = @{
                ServerPort = $ServerPort
            }
        }

        try {
            $defaultConf | ConvertTo-Json -Depth 5 | Set-Content -Path $confPath -Encoding UTF8
            Write-Host "✓ webport.conf skapad med ServerPort=$ServerPort" -ForegroundColor Green
        }
        catch {
            throw "Kunde inte skriva webport.conf → $($_.Exception.Message)"
        }

        return $ServerPort
    }

    try {
        $confRaw = Get-Content $confPath -Raw -ErrorAction Stop
    }
    catch {
        throw "Kunde inte läsa webport.conf → $($_.Exception.Message)"
    }

    try {
        $conf = $confRaw | ConvertFrom-Json -ErrorAction Stop
    }
    catch {
        Write-Host "⚠ webport.conf är korrupt JSON – återställer minimal struktur" -ForegroundColor Yellow

        $conf = @{
            default = @{
                ServerPort = $ServerPort
            }
        }
    }

    # Säkerställ sektionen "default"
    if (-not $conf.default) {
        $conf | Add-Member -MemberType NoteProperty -Name "default" -Value @{ ServerPort = $ServerPort }
    }

    # Uppdatera port
    $conf.default.ServerPort = $ServerPort

    try {
        $conf | ConvertTo-Json -Depth 10 |
            Set-Content -Path $confPath -Encoding UTF8

        Write-Host "✓ WebPort ServerPort uppdaterad → $ServerPort" -ForegroundColor Green
    }
    catch {
        throw "Kunde inte skriva uppdaterad webport.conf → $($_.Exception.Message)"
    }

    return $ServerPort
}

function Normalize-Pem {
    param([string]$pem)

    if ([string]::IsNullOrWhiteSpace($pem)) {
        return ""
    }

    $lines = $pem.Trim() -split "\r?\n"
    $lines = $lines | Where-Object { $_.Trim() -ne "" }
    return ($lines -join "`n")
}

function Test-OpenSSL {
    $script:OpenSslDiagnostics = @()
    $candidates = New-Object System.Collections.Generic.List[string]

    $cmd = Get-Command "openssl" -ErrorAction SilentlyContinue
    if ($cmd -and $cmd.Source) {
        [void]$candidates.Add($cmd.Source)
    }

    $commonPaths = @(
        "C:\Program Files\OpenSSL-Win64\bin\openssl.exe",
        "C:\Program Files\OpenSSL-Win32\bin\openssl.exe",
        "C:\OpenSSL-Win64\bin\openssl.exe",
        "C:\OpenSSL-Win32\bin\openssl.exe"
    )

    foreach ($path in $commonPaths) {
        if ((Test-Path -LiteralPath $path) -and -not $candidates.Contains($path)) {
            [void]$candidates.Add($path)
        }
    }

    foreach ($candidate in $candidates) {
        try {
            & $candidate version 2>$null | Out-Null
            $exitCode = $LASTEXITCODE
            if ($exitCode -eq 0) {
                return $candidate
            }

            $script:OpenSslDiagnostics += "OpenSSL hittad men kunde inte köras: $candidate (exitkod: $exitCode)"
        }
        catch {
            $script:OpenSslDiagnostics += "OpenSSL startfel: $candidate ($($_.Exception.Message))"
        }
    }

    return $null
}

function Assert-OpenSslExit {
    param(
        [Parameter(Mandatory = $true)][int]$ExitCode,
        [Parameter(Mandatory = $true)][string]$Operation,
        [Parameter(Mandatory = $true)][string]$OpenSslPath,
        [string]$ExpectedOutputPath
    )

    if ($ExitCode -eq -1073741515) {
        throw "OpenSSL kunde inte starta under '$Operation' (exitkod: $ExitCode). Det brukar betyda saknad DLL/runtime. Installera OpenSSL Win64 + Microsoft Visual C++ Redistributable x64 och prova igen. OpenSSL: $OpenSslPath"
    }

    if ($ExitCode -ne 0) {
        throw "OpenSSL-fel under '$Operation' (exitkod: $ExitCode). OpenSSL: $OpenSslPath"
    }

    if ($ExpectedOutputPath -and -not (Test-Path -LiteralPath $ExpectedOutputPath)) {
        throw "OpenSSL slutförde '$Operation' utan felkod men output-filen saknas: $ExpectedOutputPath"
    }
}

function ConvertTo-WindowsCommandLineArgument {
    [CmdletBinding()]
    param(
        [AllowNull()]
        [string]$Value
    )

    if ($null -eq $Value -or $Value.Length -eq 0) {
        return '""'
    }

    if ($Value -notmatch '[\s"]') {
        return $Value
    }

    $sb = New-Object System.Text.StringBuilder
    [void]$sb.Append('"')
    $backslashCount = 0

    foreach ($ch in $Value.ToCharArray()) {
        if ($ch -eq '\') {
            $backslashCount++
            continue
        }

        if ($ch -eq '"') {
            [void]$sb.Append(([char]92), ($backslashCount * 2) + 1)
            [void]$sb.Append('"')
            $backslashCount = 0
            continue
        }

        if ($backslashCount -gt 0) {
            [void]$sb.Append(([char]92), $backslashCount)
            $backslashCount = 0
        }

        [void]$sb.Append($ch)
    }

    if ($backslashCount -gt 0) {
        [void]$sb.Append(([char]92), $backslashCount * 2)
    }

    [void]$sb.Append('"')
    return $sb.ToString()
}

function Test-VcRedistX64Installed {
    $regPaths = @(
        "HKLM:\SOFTWARE\Microsoft\VisualStudio\14.0\VC\Runtimes\x64",
        "HKLM:\SOFTWARE\WOW6432Node\Microsoft\VisualStudio\14.0\VC\Runtimes\x64"
    )

    foreach ($regPath in $regPaths) {
        if (-not (Test-Path -LiteralPath $regPath)) {
            continue
        }

        try {
            $item = Get-ItemProperty -Path $regPath -ErrorAction Stop
            if ($item.Installed -eq 1) {
                return [pscustomobject]@{
                    Installed = $true
                    Version = [string]$item.Version
                    RegistryPath = $regPath
                }
            }
        }
        catch {
            continue
        }
    }

    return [pscustomobject]@{
        Installed = $false
        Version = $null
        RegistryPath = $null
    }
}

function Ensure-VcRedistX64 {
    [CmdletBinding()]
    param(
        [string]$DownloadUrl = "https://aka.ms/vc14/vc_redist.x64.exe"
    )

    $vcState = Test-VcRedistX64Installed
    if ($vcState.Installed) {
        Add-Log "VC++ x64 runtime hittades. Version: $($vcState.Version)"
        ok "VC++ x64 runtime installerad (version $($vcState.Version))"
        return
    }

    warn "Microsoft Visual C++ Redistributable x64 saknas."
    Add-Log "VC++ x64 runtime saknas."

    $answer = Read-Host "VC++ runtime krävs för OpenSSL. Vill du installera nu? (J/N)"
    if ($answer -notmatch '^(?i)(j|y|ja|yes)$') {
        throw "VC++ runtime installerades inte. Avbryter eftersom OpenSSL annars kan fallera."
    }

    $installerPath = Join-Path $env:TEMP "vc_redist.x64.exe"
    Add-Log "Laddar ner VC++ installer från: $DownloadUrl"
    step "Laddar ner vc_redist.x64.exe"
    Invoke-WebRequest -Uri $DownloadUrl -OutFile $installerPath -UseBasicParsing -ErrorAction Stop

    if (-not (Test-Path -LiteralPath $installerPath)) {
        throw "Nedladdning misslyckades: $installerPath skapades inte."
    }

    Add-Log "Startar VC++ installation: $installerPath"
    step "Installerar Microsoft Visual C++ x64 runtime"
    $proc = Start-Process -FilePath $installerPath -ArgumentList "/install", "/passive", "/norestart" -Verb RunAs -Wait -PassThru
    Add-Log "VC++ installer exitkod: $($proc.ExitCode)"

    if ($proc.ExitCode -notin 0, 1638, 1641, 3010) {
        throw "VC++ installation misslyckades (exitkod: $($proc.ExitCode))."
    }

    $vcState = Test-VcRedistX64Installed
    if (-not $vcState.Installed) {
        throw "VC++ installation verkar inte ha slutförts korrekt. Runtime hittades inte efter installation."
    }

    if ($proc.ExitCode -in 1641, 3010) {
        warn "VC++ installerades, men en omstart rekommenderas (exitkod: $($proc.ExitCode))."
    }
    else {
        ok "VC++ x64 runtime installerad (version $($vcState.Version))"
    }
}

function Upsert-WebPortSetting {
    param(
        [System.Data.SQLite.SQLiteConnection]$Conn,
        [string]$Key,
        [string]$Value,
        [string]$DeviceGuid
    )

    $cmd = $Conn.CreateCommand()
    $cmd.CommandText = "SELECT COUNT(*) FROM settings WHERE Key=@k"
    $cmd.Parameters.AddWithValue("@k",$Key) | Out-Null
    $exists = $cmd.ExecuteScalar()

    if ($exists -gt 0) {
        $cmd = $Conn.CreateCommand()
        $cmd.CommandText = "UPDATE settings SET Value=@v WHERE Key=@k"
        $cmd.Parameters.AddWithValue("@k",$Key) | Out-Null
        $cmd.Parameters.AddWithValue("@v",$Value) | Out-Null
        $cmd.ExecuteNonQuery() | Out-Null
    }
    else {
        $cmd = $Conn.CreateCommand()
        $cmd.CommandText = "INSERT INTO settings (Key,Value,DeviceGuid) VALUES (@k,@v,@dg)"
        $cmd.Parameters.AddWithValue("@k",$Key) | Out-Null
        $cmd.Parameters.AddWithValue("@v",$Value) | Out-Null
        $cmd.Parameters.AddWithValue("@dg",$DeviceGuid) | Out-Null
        $cmd.ExecuteNonQuery() | Out-Null
    }
}

function Update-WebPortCertChain {
    param(
        [string]$LeafPem,
        [string]$IntermediatePem,
        [string]$RootPem,
        [string]$DeviceGuid
    )

    $LeafNorm = Normalize-Pem $LeafPem
    $InterNorm = Normalize-Pem $IntermediatePem
    $RootNorm = Normalize-Pem $RootPem

    Add-Type -Path $SqliteDllPath 

    $conn = New-Object System.Data.SQLite.SQLiteConnection("Data Source=$WebPortDbPath;")
    $conn.Open()

    try {
        Upsert-WebPortSetting -Conn $conn -Key "SSLCAPC" -Value $LeafNorm -DeviceGuid $DeviceGuid
        Upsert-WebPortSetting -Conn $conn -Key "SSLCAIC" -Value $InterNorm -DeviceGuid $DeviceGuid
        Upsert-WebPortSetting -Conn $conn -Key "SSLCARC" -Value $RootNorm -DeviceGuid $DeviceGuid
    }
    finally {
        $conn.Close()
    }

    ok "WebPort DB uppdaterad med cert chain"
}

function Reset-WebPortSSL {
    [CmdletBinding()]
    param()

    Write-Host ""
    Write-Host "   ⚠ Failsafe – rensar SSL-relaterade fält i WebPort DB…" -ForegroundColor Yellow

    if (!(Test-Path $SqliteDllPath)) { throw "saknar SQLite DLL: $SqliteDllPath" }
    if (!(Test-Path $WebPortDbPath)) { throw "saknar DB: $WebPortDbPath" }

    Add-Type -Path $SqliteDllPath

    $conn = New-Object System.Data.SQLite.SQLiteConnection("Data Source=$WebPortDbPath;")
    $conn.Open()

    try {
        # Läs DeviceGuid
        $cmd = $conn.CreateCommand()
        $cmd.CommandText = "SELECT DeviceGuid FROM settings LIMIT 1"
        $dg = $cmd.ExecuteScalar()

        if ([string]::IsNullOrWhiteSpace($dg)) {
            Write-Warning "Ingen DeviceGuid hittades – fortsätter ändå."
            $dg = ""
        }

        function ClearKey([string]$key) {
            $cmd = $conn.CreateCommand()
            $cmd.CommandText = "SELECT COUNT(*) FROM settings WHERE Key=@k"
            $cmd.Parameters.AddWithValue("@k",$key) | Out-Null
            $exists = $cmd.ExecuteScalar()

            if ($exists -gt 0) {
                # UPDATE
                $cmd = $conn.CreateCommand()
                $cmd.CommandText = "UPDATE settings SET Value='' WHERE Key=@k"
                $cmd.Parameters.AddWithValue("@k",$key) | Out-Null
                $cmd.ExecuteNonQuery() | Out-Null
                Write-Host "  Rensade $key"
            }
            else {
                # INSERT tomt värde
                $cmd = $conn.CreateCommand()
                $cmd.CommandText = "INSERT INTO settings (Key,Value,DeviceGuid) VALUES (@k,'',@dg)"
                $cmd.Parameters.AddWithValue("@k",$key) | Out-Null
                $cmd.Parameters.AddWithValue("@dg",$dg) | Out-Null
                $cmd.ExecuteNonQuery() | Out-Null
                Write-Host "  $key saknades → skapad tom"
            }
        }

        ClearKey "SSLCSR"
        ClearKey "SSLPPK"
        ClearKey "SSLCAPC"
        ClearKey "SSLCAIC"
        ClearKey "SSLCARC"
        ClearKey "SSLCP"

    }
    finally {
        $conn.Close()
    }

    Write-Host ""
    Write-Host "   ✓ SSL-data har rensats från WebPort DB." -ForegroundColor Green
    Write-Host ""
}

function Restart-WebPort {
    [CmdletBinding()]
    param()

    Write-Host ""
    Write-Host "   🔄 Återstartar WebPort…" -ForegroundColor Cyan

    # Konstant sökväg enligt installation
    $webPortExe  = "$WebPortProgPath\WebPortServer.exe"
    $serviceName = "WebPortServer"
    $processName = "WebPortServer.exe"

    $wasService = $false
    $procBefore = $false

    # ============================
    # Stoppa service
    # ============================
    $svc = Get-Service -Name $serviceName -ErrorAction SilentlyContinue
    if ($svc -and $svc.Status -eq 'Running') {
        Write-Host "   ⏸ Stoppar service: $serviceName"
        Stop-Service $serviceName -Force
        $wasService = $true
    }

    # ============================
    # Stoppa EXE om ingen service stoppades
    # ============================
    #if (-not $wasService) {
        $p = Get-Process -Name ($processName -replace ".exe","") -ErrorAction SilentlyContinue
        if ($p) {
            Write-Host "   ⏸ Stoppar process: $processName"
            Stop-Process -Id $p.Id -Force
            $procBefore = $true
        }
    #}

    Start-Sleep -Seconds 2

    if ($wasService) {
        Write-Host "   ▶ Startar service: $serviceName"
        Start-Service $serviceName
        Write-Host "   ▶ Startar process: $webPortExe"
        Start-Process $webPortExe
    }
    elseif ($procBefore) {
        Write-Host "   ▶ Startar process: $webPortExe"
        Start-Process $webPortExe
    }
    else {
        Write-Host "   ℹ WebPort var inte igång tidigare → startas ej"
    }

    Write-Host "   ✓ WebPort omstart klar." -ForegroundColor Green
    Write-Host ""
}

function Read-PluginArgsFile {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [string]$Path
    )

    if (-not (Test-Path $Path)) {
        throw "PluginArgs-fil hittades inte: $Path"
    }

    $raw = Get-Content -Path $Path -Raw

    # 1) JSON-format
    try {
        $json = $raw | ConvertFrom-Json -ErrorAction Stop
        Write-Host "   ✓ PluginArgs importerad från JSON → $Path" -ForegroundColor Green
        return $json
    }
    catch {
        Write-Host "   ℹ Ej JSON → försöker tolka radvis Key=Value" -ForegroundColor Yellow
    }

    # 2) INI-liknande format "Key=Value"
    $args = @{}

    $lines = $raw -split "`r?`n"
    foreach ($ln in $lines) {
        if ($ln -match "^\s*#") { continue }
        if ($ln.Trim() -eq "") { continue }

        $kv = $ln -split "=",2
        if ($kv.Count -ne 2) { continue }

        $key = $kv[0].Trim()
        $val = $kv[1].Trim()

        # Försök auto-typning
        if ($val -match "^\d+$")       { $val = [int]$val }
        elseif ($val -match "^(true|false)$") { $val = [bool]$val }

        $args[$key] = $val
    }

    if ($args.Count -gt 0) {
        Write-Host "   ✓ PluginArgs importerad som Key=Value-format → $Path" -ForegroundColor Green
        return $args
    }

    throw "Kunde inte tolka PluginArgs från: $Path"
}

function Ensure-WebPortFirewallRule {
    param(
        [int]$ServerPort
    )

    if (-not $ServerPort) {
        throw "ServerPort är ej angiven"
    }

    $ruleName = "WebPort TCP $ServerPort"

    # Finns redan?
    $existing = Get-NetFirewallRule -DisplayName $ruleName -ErrorAction SilentlyContinue
    if ($existing) {
        Write-Host "   ✓ Brandväggsregel finns redan: $ruleName" -ForegroundColor Green
        return
    }

    Write-Host "   ➕ Skapar brandväggsregel för inkommande TCP $ServerPort…" -ForegroundColor Cyan

    New-NetFirewallRule `
        -DisplayName $ruleName `
        -Direction Inbound `
        -Action Allow `
        -Enabled True `
        -Protocol TCP `
        -LocalPort $ServerPort `
        -Profile Any `
        | Out-Null

    Write-Host "   ✓ Brandväggsregel skapad: $ruleName" -ForegroundColor Green
}

function Ensure-PoshAcme {
    [CmdletBinding()]
    param()

    Write-Host "   🔍 Kontrollerar Posh-ACME…" -ForegroundColor Cyan

    # Finns modulen redan installerad?
    $mod = Get-Module -Name Posh-ACME -ListAvailable -ErrorAction SilentlyContinue

    if (-not $mod) {
        Write-Host "   ⚠ Posh-ACME saknas → installerar…" -ForegroundColor Yellow

        try {
            Install-Module Posh-ACME -Scope AllUsers -Force -AllowClobber -ErrorAction Stop
            Write-Host "   ✓ Posh-ACME installerad" -ForegroundColor Green
        }
        catch {
            Write-Host "   ❌ Kunde inte installera Posh-ACME:" -ForegroundColor Red
            Write-Host $_.Exception.Message
            throw
        }
    }
    else {
        Write-Host "   ✓ Posh-ACME är installerad" -ForegroundColor Green
    }

    # Importera
    try {
        Import-Module Posh-ACME -ErrorAction Stop
        Write-Host "   ✓ Modul importerad" -ForegroundColor Green
    }
    catch {
        Write-Host "   ❌ Kunde inte importera Posh-ACME" -ForegroundColor Red
        throw
    }
}

function Ensure-AzModule {
    if (-not (Get-Module -ListAvailable -Name Az.Accounts)) {
        Write-Host "   ⚠ Installing Az.Accounts …" -ForegroundColor Yellow
        Install-Module Az.Accounts -Force -Scope AllUsers
    }

    # Optional but recommended if access token fails
    if (-not (Get-Module -ListAvailable -Name Az.Resources)) {
        Write-Host "   ⚠ Installing Az.Resources …" -ForegroundColor Yellow
        Install-Module Az.Resources -Force -Scope AllUsers
    }

    Import-Module Az.Accounts  -ErrorAction Stop
    Import-Module Az.Resources -ErrorAction SilentlyContinue

    Write-Host "   ✓ Az modules loaded" -ForegroundColor Green
}

function Send-WebPortMail {
    param(
        [Parameter(Mandatory=$true)] [string]$To,
        [Parameter(Mandatory=$true)] [string]$Subject,
        [Parameter(Mandatory=$true)] [string]$Body
    )

    $Settings = Read-WebPortSettings

    $smtpServer    = $Settings["smtpserver"]
    $smtpPort      = [int]$Settings["smtpport"]
    $smtpSsl       = [bool]$Settings["smtpssl"]
    $smtpEncoding  = $Settings["smtpencoding"]
    $smtpFrom      = $Settings["smtpfrom"]
    $smtpUser      = $Settings["smtpuser"]

    if (-not $smtpServer) { throw "SMTP server saknas i WebPort DB." }
    if (-not $smtpFrom)   { throw "SMTP avsändaradress saknas i WebPort DB." }

    try {
        # TODO: ersätt med riktig dekryptering av smtppassword senare:
        $SmtpPwd = ConvertTo-SecureString -String 'vH0z1oix73VfSaLs' -AsPlainText -Force
    }
    catch {
        throw "Kunde inte dekryptera SMTP-lösenordet (smtppassword) i databasen."
    }

    $credential = New-Object System.Management.Automation.PSCredential($smtpUser, $SmtpPwd)
    Write-Host "smtpUser: $smtpUser to: $To subject: $Subject server: $smtpServer port: $smtpPort ssl: $smtpSsl from: $smtpFrom"

    # Bygg mailmeddelande
    $msg = New-Object System.Net.Mail.MailMessage
    $msg.From = $smtpFrom
    $msg.Subject = $Subject
    $msg.Body = $Body

    # 🟩 SPLITTA MOTTAGARE VID ';'
    $recipients = $To -split ";" | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne "" }

    if ($recipients.Count -eq 0) {
        throw "Inga giltiga mottagare i TO-parametern."
    }

    foreach ($rcpt in $recipients) {
        try {
            $null = $msg.To.Add($rcpt)
        }
        catch {
            Write-Warning "Ogiltig e-postadress ignoreras: $rcpt"
        }
    }

    # Body encoding
    try {
        if ($smtpEncoding) {
            $msg.BodyEncoding = [System.Text.Encoding]::GetEncoding($smtpEncoding)
        }
        else {
            $msg.BodyEncoding = [System.Text.Encoding]::UTF8
        }
    }
    catch {
        Write-Warning "Kunde inte använda encoding '$smtpEncoding'. Använder UTF-8."
        $msg.BodyEncoding = [System.Text.Encoding]::UTF8
    }

    # SMTP-klient
    $smtp = New-Object System.Net.Mail.SmtpClient($smtpServer, $smtpPort)
    $smtp.EnableSsl = $smtpSsl
    $smtp.Credentials = $credential
    $smtp.Timeout = 15000   # 15 sek

    try {
        $smtp.Send($msg)
        Write-Host "✓ Mail skickat till: $($recipients -join ', ')" -ForegroundColor Green
        return $true
    }
    catch {
        Write-Host "✖ Misslyckades att skicka mail:" -ForegroundColor Red
        Write-Host "  Fel: $($_.Exception.Message)"
        if ($_.Exception.InnerException) {
            Write-Host "  Inner: $($_.Exception.InnerException.Message)"
        }
        return $false
    }
}


function Add-Log {
    param([string]$Text)
    $IssueCertLog.AppendLine("[$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')] $Text") | Out-Null
}

function Stop-TranscriptSafe {
    if (-not (Get-Variable -Name TranscriptFile -Scope Script -ErrorAction SilentlyContinue)) {
        return
    }

    try {
        Stop-Transcript | Out-Null
        Write-Host "📄 Loggning stopppad → $TranscriptFile" -ForegroundColor Cyan
    }
    catch {
        # Transcript may already be stopped; ignore to keep shutdown flow clean.
    }
}

$ScriptRoot = Split-Path -Parent $PSCommandPath
$SecurePasswordPath = Join-Path $ScriptRoot "securePassword.xml"


$IssueCertLog = New-Object System.Text.StringBuilder
$UseSecretStore = $true
if ($UseSecretStore -and !$failsafe) {

    Write-Host "==> SecretStore" -ForegroundColor Cyan

    # Säkerställ moduler
    if (-not (Get-Module -ListAvailable -Name Microsoft.PowerShell.SecretManagement)) {
        Install-Module Microsoft.PowerShell.SecretManagement -Force -Scope AllUsers
    }
    if (-not (Get-Module -ListAvailable -Name Microsoft.PowerShell.SecretStore)) {
        Install-Module Microsoft.PowerShell.SecretStore -Force -Scope AllUsers
    }

    Import-Module Microsoft.PowerShell.SecretManagement
    Import-Module Microsoft.PowerShell.SecretStore

    # Registrera SecretStore som default vault
    if (-not (Get-SecretVault | Where-Object { $_.Name -eq "SecretStore" })) {
        Register-SecretVault `
            -Name SecretStore `
            -ModuleName Microsoft.PowerShell.SecretStore `
            -DefaultVault `
            -ErrorAction Stop

        Write-Host "✓ SecretStore registrerad som default vault" -ForegroundColor Green
    }
    else {
        # Om redan registrerad men inte default: sätt den som default
        $vault = Get-SecretVault | Where-Object { $_.Name -eq "SecretStore" }
        if (-not $vault.IsDefault) {
            Set-DefaultSecretVault -Name SecretStore
            Write-Host "✓ SecretStore satt som default vault" -ForegroundColor Green
        }
    }


    # Kontrollera lösenordsfil
    if (-not (Test-Path $SecurePasswordPath)) {
        Write-Host "   ⚠ securePasswordPath saknas → skapar..." -ForegroundColor Yellow

        $pwd = Read-Host "Ange SecretStore-lösenord för export" -AsSecureString
        $pwd | Export-CliXml -Path $SecurePasswordPath

        Write-Host "   ✓ Lösenord exporterat till $SecurePasswordPath" -ForegroundColor Green
    }

    # Lås upp SecretStore
    $password = Import-CliXml -Path $SecurePasswordPath
    Unlock-SecretStore -Password $password -ErrorAction Stop
    Write-Host "   ✓ SecretStore upplåst" -ForegroundColor Green

    try {
        $PluginArgs = Get-Secret -Name "PluginArgs" -AsPlainText
        Write-Host "   ✓ PluginArgs lästa från SecretStore" -ForegroundColor Green
    }
    catch {
Write-Host @"
Secret 'PluginArgs' saknas i SecretStore.

Du måste skapa PluginArgs baserat på DNS-pluginet du använder.
Följ plugin-guiden för ditt DNS-system:
    https://poshac.me/docs/v4/Plugins/

Spara pArgs i SecretStore:
-------------------------------------------------------------
Set-Secret -Name PluginArgs -Secret `$pArgs

När pArgs är korrekt inlagda i SecretStore, kör scriptet igen.
"@
          throw "Secret 'PluginArgs' saknas i SecretStore. Skapa och lägg till enligt instruktioner ovan."        
    }

    try {
        $PfxPass = Get-Secret -Name "PfxPass" -AsPlainText
        Write-Host "   ✓ PfxPass läst från SecretStore" -ForegroundColor Green
    }
    catch {
        throw "Secret 'PfxPass' saknas i SecretStore. Lägg till med: Set-Secret -Name PfxPass -Secret 'hemligt'"
    }

    try {
        $SmtpPwd = Get-Secret -Name "SmtpPwd" -AsPlainText
        Write-Host "   ✓ SmtpPwd läst från SecretStore" -ForegroundColor Green
    }
    catch {
        throw "Secret 'SmtpPwd' saknas i SecretStore. Lägg till med: Set-Secret -Name SmtpPwd -Secret 'hemligt'"
    }
}
$EnableLogging = $true
if ($EnableLogging -and !$failsafe) {

    # Hämta scriptets mapp och namn
    $ScriptRoot = Split-Path -Parent $PSCommandPath
    $ScriptName = [IO.Path]::GetFileNameWithoutExtension($PSCommandPath)

    # Loggmapp per script:  <ScriptRoot>\<ScriptName>-logs\
    $LogFolder = Join-Path $ScriptRoot "$ScriptName-logs"

    # Skapa mapp om den saknas
    if (-not (Test-Path $LogFolder)) {
        New-Item -Path $LogFolder -ItemType Directory | Out-Null
    }

    # Rensa loggfiler äldre än 100 dagar
    Get-ChildItem -Path $LogFolder -File |
        Where-Object { $_.LastWriteTime -lt (Get-Date).AddDays(-100) } |
        Remove-Item -Force -ErrorAction SilentlyContinue

    # Loggfilens namn: Scriptname-YYYYMMDD-HHMMSS.txt
    $Timestamp = (Get-Date -Format "yyyyMMdd-HHmmss")
    $TranscriptFile = Join-Path $LogFolder "$ScriptName-$Timestamp.txt"

    # Starta transcript
    Start-Transcript -Path $TranscriptFile -Append | Out-Null

    Write-Host "📄 Loggning startad → $TranscriptFile" -ForegroundColor Cyan

}
# Kontroll: PowerShell version
$minPS = [Version]"7.0.0"
if ($PSVersionTable.PSVersion -lt $minPS) {
    Write-Host "   ❌ Detta script kräver PowerShell $minPS eller senare." -ForegroundColor Red
    Write-Host "   Du kör: $($PSVersionTable.PSVersion)"
    Write-Host "   Installera senaste PowerShell här:"
    Write-Host "   https://learn.microsoft.com/powershell/scripting/install/installing-powershell"
    throw "PowerShell version för låg"
}
Write-Host "   ✓ PowerShell version OK: $($PSVersionTable.PSVersion)" -ForegroundColor Green

# Kontroll: Adminrättigheter
$IsAdmin = ([Security.Principal.WindowsPrincipal] `
    [Security.Principal.WindowsIdentity]::GetCurrent() `
    ).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)

if (-not $IsAdmin) {
    Write-Host "   ❌ Scriptet måste köras som administratör." -ForegroundColor Red
    Write-Host "   "
    Write-Host "   Högerklicka → 'Run as Administrator'"
    throw "Ej administratör"
}
Write-Host "   ✓ Administratörsrättigheter OK" -ForegroundColor Green

if ($ServerPort -ne (Get-WebPortServerPort -WebPortDataPath $WebPortDataPath)) {
    step "Sätter WebPort ServerPort till $ServerPort"
    Write-Host "   ✓ Sätter WebPort ServerPort till $ServerPort" -ForegroundColor Green
    $newPort = Set-WebPortServerPort -WebPortDataPath $WebPortDataPath -ServerPort $ServerPort
    Ensure-WebPortFirewallRule -ServerPort $newPort
    Restart-WebPort
    Write-Host "`n✓ WebPort cleanup klar" -ForegroundColor Green
    ok "WebPort ServerPort satt till $newPort"
}

if (!$failsafe) {
    step "Säkerställer att PoshAcme är installerad"
    Ensure-PoshAcme
    Import-Module Posh-ACME -ErrorAction Stop | Out-Null
    ok "PoshAcme är installerad"

    step "Läser WebPort DB"
    $Settings   = Read-WebPortSettings
    $SSLCN      = $Settings["SSLCN"]
    $SSLCSR     = $Settings["SSLCSR"]
    $DeviceGuid = $Settings["DeviceGuid"]
    $SSLCP      = $Settings["SSLCP"]


    if ([string]::IsNullOrWhiteSpace($SSLCP)) {
        Write-Host "   ✖ Inget Cert-lösenord hittad i WebPort-databasen." -ForegroundColor Red
    }
        
    if ([string]::IsNullOrWhiteSpace($SSLCSR)) {
        Write-Host "   ✖ Ingen CSR (SSLCSR) hittad i WebPort-databasen." -ForegroundColor Red
    }

    if ([string]::IsNullOrWhiteSpace($SSLCSR) -or [string]::IsNullOrWhiteSpace($SSLCP)) {
        Write-Host ""
        Write-Host "För att fortsätta måste du skapa en CSR i WebPorts GUI:" -ForegroundColor Yellow
        Write-Host ""
        Write-Host "   1) Logga in i WebPort"
        Write-Host "   2) Gå till: Systeminställningar → Server → SSL Certifikat"
        Write-Host "   3) Ange:"
        Write-Host "        • Common Name (CN) = fullt domännamn"
        Write-Host "        • SAN (Alternative Names) om fler namn behövs"
        Write-Host "        • Lösenord"
        Write-Host "   4) Klicka: Spara"
        Write-Host "   5) Gå tillbaka:  SSL Certifikat"
        Write-Host "   6) Klicka: Create CSR"
        Write-Host ""
        Write-Host "CSR kommer därefter att lagras automatiskt i databasen (settings → SSLCSR)."
        Write-Host ""
        Write-Host "Kör sedan skriptet igen."
        Write-Host ""

        Write-Error "CSR saknas — skapa via WebPort GUI innan du fortsätter."
    }

    if (!$SSLCSR) { throw "Ingen CSR (SSLCSR) hittad i WebPort DB. Skapa via GUI först." }

    # Domain = CN = första entry i SSLCN
    $CN = $SSLCN -split ";" | Select-Object -First 1
    Write-Host "   CN = $CN" -ForegroundColor Green

    # Skriv CSR till fil
    $csrFile = Join-Path $env:TEMP "wp.csr"
    Set-Content $csrFile $SSLCSR -Encoding ascii
    ok "CSR skriven till $csrFile"
    
    step "Läser WebPort conf-file $WebPortDataPath\webport.conf"

    if (!(Test-Path "$WebPortDataPath\webport.conf")) {
        throw "webport.conf saknas: $confPath"
    }

    $conf = Get-Content "$WebPortDataPath\webport.conf" -Raw | ConvertFrom-Json
    $ServerPort = $conf.default.ServerPort
    Write-Host "   ServerPort = $ServerPort" -ForegroundColor Green
    Ensure-WebPortFirewallRule -ServerPort $ServerPort
    ok "webport.conf läst"
}

if ($failsafe){
    $Settings   = Read-WebPortSettings

    Reset-WebPortSSL
    Set-WebPortServerPort -WebPortDataPath $WebPortDataPath -ServerPort 8090

    if (Test-Path "$WebPortDataPath\webport.p12") {
        Write-Host "Tar bort P12 → $WebPortDataPath\webport.p12"
        Remove-Item "$WebPortDataPath\webport.p12" -Force
    }
    else {
        Write-Host "Ingen P12 hittad → hoppar över"
    }

    # RENSAR CERT I KEYSTORE
    $SSLCN = $Settings["SSLCN"]

    if ($SSLCN) {
        Write-Host "   SSLCN=$SSLCN"

        # CN kan innehålla ";SAN..." → ta första
        $CN = ($SSLCN -split ";")[0]

        Write-Host "   Rensar cert i certstore för CN=$CN"

        $items = Get-ChildItem Cert:\LocalMachine\My |
            Where-Object { $_.Subject -eq "CN=$CN" }

        foreach ($c in $items) {
            Write-Host "Tar bort cert: $($c.Thumbprint)"
            Remove-Item "Cert:\LocalMachine\My\$($c.Thumbprint)" -Force
        }
    }
    else {
        Write-Warning "SSLCN saknas i DB → hoppar över keystore-rensning"
    }
    Restart-WebPort
    Write-Host "   ✓ WebPort cleanup klar" -ForegroundColor Green

}

if ($CreateScheduledTask) {

    step "Skapar schemalagd uppgift för automatisering"
    $taskName = "WebPort LetsEncrypt Renewal"
    $ScriptPath = $PSCommandPath
    $ScriptDir  = Split-Path -Parent $ScriptPath

    # Ensure PowerShell 7 exists
    $pwsh = Get-Command "pwsh.exe" -ErrorAction SilentlyContinue
    if (-not $pwsh) {
        throw "PowerShell 7 (pwsh.exe) not found. Install from: https://learn.microsoft.com/powershell/"
    }

    #
    # Build a robust command line for Task Scheduler.
    # This avoids broken parsing when values end with backslash.
    #
    $effectiveDnsPlugin = if ([string]::IsNullOrWhiteSpace($DnsPlugin)) { 'Azure' } else { $DnsPlugin }

    $argsList = New-Object System.Collections.Generic.List[string]
    $argsList.Add('-NoLogo')
    $argsList.Add('-NoProfile')
    $argsList.Add('-File')
    $argsList.Add($ScriptPath)
    $argsList.Add('-IssueCert')
    $argsList.Add('-InstallPfx')
    $argsList.Add('-DnsPlugin')
    $argsList.Add($effectiveDnsPlugin)
    $argsList.Add('-ServerPort')
    $argsList.Add([string]$ServerPort)
    $argsList.Add('-WebPortDataPath')
    $argsList.Add($WebPortDataPath)
    $argsList.Add('-WebPortProgPath')
    $argsList.Add($WebPortProgPath)

    if (-not [string]::IsNullOrWhiteSpace($Sendmail)) {
        $argsList.Add('-Sendmail')
        $argsList.Add($Sendmail)
    }

    $argumentString = ($argsList | ForEach-Object { ConvertTo-WindowsCommandLineArgument -Value $_ }) -join " "

    # Scheduled Task action
    $action = New-ScheduledTaskAction -Execute $pwsh.Source -Argument $argumentString -WorkingDirectory $ScriptDir

    # Weekly at 02:00
    $trigger = New-ScheduledTaskTrigger -Weekly -DaysOfWeek Sunday -At 2:00am

    # Hämta nuvarande användare
    $currentUser = [System.Security.Principal.WindowsIdentity]::GetCurrent().Name

    # Skapa principal som current user, med S4U-logintyp (kräver ej lösenord)
    $principal = New-ScheduledTaskPrincipal `
        -UserId $currentUser `
        -RunLevel Highest `
        -LogonType S4U

    $settings = New-ScheduledTaskSettingsSet -ExecutionTimeLimit (New-TimeSpan -Minutes 5)

    # Create task
    $task = New-ScheduledTask -Action $action -Trigger $trigger -Principal $principal -Settings $settings

    Register-ScheduledTask -TaskName $taskName -InputObject $task -Force

    ok "Schemalagd uppgift skapad: $taskName "
    Stop-TranscriptSafe
    return
}

if ($IssueCert) {

    step "Startar IssueCert-process"
    Add-Log "Startar IssueCert-process"

    $Settings = Read-WebPortSettings
    $SSLCN = $Settings["SSLCN"]

    try {

        
        $PluginArgs = Get-Secret -Name PluginArgs -AsPlainText 
        $PfxPass = Get-Secret -Name PfxPass    -AsPlainText
        $SmtpPwd = Get-Secret -Name SmtpPwd    -AsPlainText
        

        if (($PluginArgs) -and ($PfxPass) -and ($SmtpPwd)) {

            $cert = Get-ChildItem Cert:\LocalMachine\My | Where-Object { $_.Subject -like "CN=$SSLCN" }
            $daysLeft = ($cert.NotAfter - (Get-Date)).Days
            Add-Log "Cert finns: $($cert.Thumbprint), giltigt till: $($cert.NotAfter), dagar kvar: $daysLeft"

            if ($daysLeft -lt 30 -or -not $cert) { 

                Add-Log "Förnyar cert via ACME (CSR mode)"
                
                New-PACertificate `
                    -CSR $csrFile `
                    -DnsPlugin $DnsPlugin `
                    -PluginArgs $PluginArgs `
                    -acceptTOS `
                    -Verbose `
                    -debug

                #Error parsing certificate request: asn1: syntax error: sequence truncated

                Add-Log "New-PACertificate körd OK"

                Add-Log "Kör Complete-PAOrder"
                Complete-PAOrder

                Add-Log "Complete-PAOrder klar"

                $pa = Get-PACertificate
                if (!$pa) {
                    Add-Log "ERROR: Get-PACertificate gav tomt resultat"
                    Add-Log "Sannolik orsak: felaktiga DNS-plugin parametrar"

                    write-host "Get-PACertificate → tomt resultat (Förmodligen fel i DNS-plugin parameter)"
                    write-host "$($PluginArgs|ConvertTo-Json)"
                }
                else {
                    Add-Log "Get-PACertificate OK: $($pa.Thumbprint)"
                    Add-Log "Certificate giltigt till: $($pa.NotAfter)"
                
                }

                # Full chain
                Add-Log "Läser FullChainFile från $($pa.FullChainFile)"
                $full = Get-Content $pa.FullChainFile -Raw

                Add-Log "Delar upp cert-kedjan"
                $certs = $full -split "-----END CERTIFICATE-----"
                $certs = $certs | ForEach-Object { ($_ + "-----END CERTIFICATE-----") } |
                Where-Object { $_ -match "BEGIN CERTIFICATE" }

                $leaf = if ($certs.Count -ge 1) { Add-Log "Leaf cert OK"; $certs[0] } else { Add-Log "Leaf saknas"; "" }
                $inter = if ($certs.Count -ge 2) { Add-Log "Intermediate cert OK"; $certs[1] } else { Add-Log "Intermediate saknas"; "" }

                # Root PEM
                $rootUrl = "https://letsencrypt.org/certs/isrgrootx1.pem.txt"
                Add-Log "Hämtar Root PEM från $rootUrl"
                $rootPem = Invoke-WebRequest -Uri $rootUrl -UseBasicParsing | Select-Object -ExpandProperty Content
                Add-Log "Root PEM hämtad"

                Update-WebPortCertChain -LeafPem $leaf -IntermediatePem $inter -RootPem $rootPem -DeviceGuid $DeviceGuid
                Add-Log "WebPort-databasen uppdaterad med cert chain"
            }
            else {
                Add-Log "Cert finns: $($cert.Thumbprint), giltigt till: $($cert.NotAfter), dagar kvar: $daysLeft" -Level Information
                Write-Host "   ✓ Cert finns och är giltigt i $daysLeft dagar → ingen förnyelse behövs" -ForegroundColor Green
                Stop-TranscriptSafe
                return
            }
            
        }
        else {
            Write-Warning "Ett eller flera secrets saknas. Avbryter steg."
        }


    }
    catch {
        Add-Log "FEL: $($_.Exception.Message)"
        if ($_.Exception.InnerException) {
            Add-Log "INNER: $($_.Exception.InnerException.Message)"
        }
        throw  # bibehåll samma felbeteende
    }
    finally {
        Add-Log "IssueCert-process avslutad"
    }

}

if ($InstallPfx) {

    Add-Log "Startar InstallPfx-process"
    step "Bygger webport.p12"
    Add-Log "Initierar byggandet av webport.p12"

    try {
        Ensure-VcRedistX64

        $openssl = Test-OpenSSL
        if (-not $openssl) {
            Add-Log "FEL: OpenSSL saknas"
            $diagText = if ($script:OpenSslDiagnostics -and $script:OpenSslDiagnostics.Count -gt 0) {
                "`nDiagnostik:`n - " + ($script:OpenSslDiagnostics -join "`n - ")
            }
            else {
                ""
            }
            throw "OpenSSL saknas eller kan inte starta – installera/repair OpenSSL + VC++ runtime. https://slproweb.com/products/Win32OpenSSL.html$diagText"
        }

        Add-Log "OpenSSL hittades: $openssl"

        $tmp = $env:TEMP
        $pfxTemp = Join-Path $tmp "webport_temp.pfx"
        $webportP12Path = Join-Path $WebPortDataPath "webport.p12"
        Add-Log "Temporär PFX-sökväg: $pfxTemp"

        # Paths för pem-material
        $privKeyPath = Join-Path $tmp "privkey.pem"
        $certPath    = Join-Path $tmp "cert.pem"
        $chainPath   = Join-Path $tmp "chain.pem"

        Add-Log "PEM paths:"
        Add-Log "  privKeyPath = $privKeyPath"
        Add-Log "  certPath    = $certPath"
        Add-Log "  chainPath   = $chainPath"

        $cert = Get-ChildItem Cert:\LocalMachine\My |
            Where-Object { $_.Subject -eq "CN=$CN" }

        if ($cert) {

            Add-Log "Cert hittades i LocalMachine\My för CN=$CN"
            Write-Host "   ✓ Cert hittades i LocalMachine\My → exporterar" -ForegroundColor Green

            Add-Log "Exporterar PFX från certstore"
            $pfxBytes = $cert.Export(
                [System.Security.Cryptography.X509Certificates.X509ContentType]::Pfx,
                $PfxPass
            )

            [System.IO.File]::WriteAllBytes($pfxTemp, $pfxBytes)
            Add-Log "Temporär PFX exporterad till $pfxTemp"

            Add-Log "Extraherar cert och key från PFX via OpenSSL"

            & $openssl pkcs12 -in  $pfxTemp -nodes -nokeys  -out $certPath    -password pass:$PfxPass
            Assert-OpenSslExit -ExitCode $LASTEXITCODE -Operation "extrahera cert.pem" -OpenSslPath $openssl -ExpectedOutputPath $certPath
            Add-Log "Extraherat cert → $certPath"

            & $openssl pkcs12 -in  $pfxTemp -nodes -nocerts -out $privKeyPath -password pass:$PfxPass
            Assert-OpenSslExit -ExitCode $LASTEXITCODE -Operation "extrahera privkey.pem" -OpenSslPath $openssl -ExpectedOutputPath $privKeyPath
            Add-Log "Extraherat privat nyckel → $privKeyPath"

            & $openssl pkcs12 -in  $pfxTemp -nodes -nokeys  -out $chainPath   -password pass:$PfxPass
            Assert-OpenSslExit -ExitCode $LASTEXITCODE -Operation "extrahera chain.pem" -OpenSslPath $openssl -ExpectedOutputPath $chainPath
            Add-Log "Extraherat chain.pem → $chainPath"
        }
        else {

            Add-Log "Cert saknas i LocalMachine\My → hämtar certdata från WebPort DB"
            Write-Host "   ⚠ Cert saknas i LocalMachine\My → hämtar material från DB"

            $Settings   = Read-WebPortSettings
            $SSLPPK  = $Settings["SSLPPK"]
            $SSLCAPC = $Settings["SSLCAPC"]
            $SSLCAIC = $Settings["SSLCAIC"]
            $SSLCARC = $Settings["SSLCARC"]

            Add-Log "DB-values:"
            Add-Log "  SSLPPK present: $([bool]$SSLPPK)"
            Add-Log "  SSLCAPC present: $([bool]$SSLCAPC)"
            Add-Log "  SSLCAIC present: $([bool]$SSLCAIC)"
            Add-Log "  SSLCARC present: $([bool]$SSLCARC)"

            if (-not $SSLPPK) {
                Add-Log "FEL: Ingen privat nyckel hittad i DB"
                throw "Ingen privat nyckel hittad i DB (SSLPPK)"
            }
            if (-not $SSLCAPC) {
                Add-Log "FEL: SSLCAPC saknas i DB"
                throw "SSLCAPC (leaf cert) saknas i DB"
            }

            Add-Log "Skriver PEM-filer från DB-innehåll"
            Set-Content -Path $privKeyPath -Value $SSLPPK   -Encoding ascii
            Set-Content -Path $certPath    -Value $SSLCAPC  -Encoding ascii

            # Bygg chain.pem
            $chainPem = ""

            if ($SSLCAIC) { 
                $chainPem += $SSLCAIC + "`n"
                Add-Log "Intermediate cert tillagd"
            }
            if ($SSLCARC) { 
                $chainPem += $SSLCARC + "`n"
                Add-Log "Root cert tillagd"
            }

            if ($chainPem -ne "") {
                Set-Content -Path $chainPath -Value $chainPem -Encoding ascii
                Add-Log "chain.pem skapad"
            }
            else {
                Write-Warning "   Ingen intermediate/root certkedja hittad i DB"
                Add-Log "Ingen intermediate/root certkedja hittad, skapar tom chain.pem"
                Set-Content -Path $chainPath -Value "" -Encoding ascii
            }
        }

        Add-Log "Kör OpenSSL export → webport.p12"

        & $openssl pkcs12 -export `
            -inkey    $privKeyPath `
            -in       $certPath `
            -certfile $chainPath `
            -out      $webportP12Path `
            -password pass:$PfxPass

        Assert-OpenSslExit -ExitCode $LASTEXITCODE -Operation "skapa webport.p12" -OpenSslPath $openssl -ExpectedOutputPath $webportP12Path

        Add-Log "webport.p12 skapad → $webportP12Path"
        ok "P12 skapad → $webportP12Path"
        step "Installerar cert i LocalMachine\My"
        Add-Log "Installerar certifikat i LocalMachine\My"
        & certutil -f -p $PfxPass -ImportPfx $webportP12Path
        if ($LASTEXITCODE -ne 0) {
            throw "certutil ImportPfx misslyckades för '$webportP12Path' (exitkod: $LASTEXITCODE)"
        }
        Add-Log "certutil ImportPfx slutförd"
        Restart-WebPort
        Add-Log "WebPort restartad efter cert-installation"
        ok "Cert installerat"
        Add-Log "InstallPfx-process avslutad OK"

    }
    catch {
        Add-Log "FEL i InstallPfx: $($_.Exception.Message)"
        if ($_.Exception.InnerException) {
            Add-Log "INNER: $($_.Exception.InnerException.Message)"
        }
        throw
    }

}

if ($Sendmail){
    step "Analysera och skicka log vid fel"
    $Settings = Read-WebPortSettings
    $SSLCN    = $Settings["SSLCN"]
    $DoSendMail = ($($IssueCertLog.ToString()) -match '(?i)(exception|error|fail|failed|timeout|denied|missing|not found|unable|could not|invalid)') 

    if ($DoSendMail) {
        step "Skickar mail till $Sendmail"
        Add-Log "Problem upptäckta i loggen → skickar mail"
        err "Problem upptäckta i loggen → skickar mail"
        $global:IssueCertLog = $IssueCertLog 
        Send-WebPortMail -To $Sendmail -Subject "$SSLCN - Problem med att förnya certifikat" -Body $IssueCertLog.ToString()
        OK "Mail skickat till $Sendmail"
    }
    else {
        Add-Log "Inga problem upptäckta i loggen → mail skickas"
        Send-WebPortMail -To $Sendmail -Subject "$SSLCN - Förnyat certifikat" -Body $IssueCertLog.ToString()
        ok "Inga problem upptäckta i loggen → mail skickas"
    }
}

Write-Host "`n✓ KLART" -ForegroundColor Green
Stop-TranscriptSafe
